apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam:::role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2VY7T201IUBA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam:::role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-20T23:07:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "848"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: da4db888-3b09-457e-aa4a-0a14ddf43fa1
